FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}

# Copy the database schema initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose port (optional if needed)
EXPOSE 3306
